# NumPy:
--> NumPy stands for Numerical Python.

--> NumPy is a Python library used for working with arrays.

--> NumPy performs Numerical_Operations

# Applications:
1) Linear Algebra

2) Statistics

3) Probability

4) Trignometric Operations(sin, cos, tan .....)

5) Matrix Manipulation

6) Logarithmic Operations

# Array:
--> It is a collection of Homogeneous Datatypes

--> The array object in NumPy is called ndarray

ndarray ----> n-dimentional array

--> Arrays are faster than list

--> Numpy is written in C/C++ language(Partially writtened in Python)

--> Arrays can be created with the help of tuples and lists

--> Supported Datatypes:- int,float,complex,str

# Why is NumPy Faster Than Lists?

--> NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

--> This behavior is called locality of reference in computer science.

--> This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# Difference Between List and Array in Python:

** List **
1) List is used to collect items that usually consist of elements of multiple data types.
2) List cannot manage arithmetic operations.
3) It consumes a larger memory.
4) It consists of elements that belong to the different data types.
5) When it comes to flexibility, the list is perfect as it allows easy modification of data.
6) In a list, the complete list can be accessed without any specific looping.
7) It favors a shorter sequence of data.


** Array **
1) An array is also a vital component that collects several items of the same data type.
2) Array can manage arithmetic operations.
3) It consumes less memory than a list.
4) It consists of elements that belong to the same data type.
5) When it comes to flexibility, the array is not suitable as it does not allow easy modification of data.
6) In an array, a loop is mandatory to access the components of the array.
7) It favors a longer sequence of data.

## How to Import Numpy:

In [7]:
import numpy as np

## Creating Numpy Arrays

In [2]:
arr=np.array([1,23.45,'advik',11+11j])
print(type(arr))
arr

<class 'numpy.ndarray'>


array(['1', '23.45', 'advik', '(11+11j)'], dtype='<U64')

## dtype='<U64'

Every nd-array has an associated data type (dtype) object.
This data type object (dtype) informs us about the layout of the array.

## Change DataTypes:

- int --> float
- float --> int
- int,float --> complex
- complex --> int & float is not possible

## int-->float

In [3]:
import numpy as np
li=[1,2,3]
arr=np.array(li,dtype=float)
arr 

array([1., 2., 3.])

## int-->complex

In [4]:
li=[1,2,3]
arr=np.array(li,dtype=complex)
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

## float-->int

In [5]:
li=[1.1,3.3,5.5]
arr=np.array(li,dtype=int)
arr

array([1, 3, 5])

## float-->complex

In [6]:
li=[1.1,3.3,5.5]
arr=np.array(li,dtype=complex)
arr

array([1.1+0.j, 3.3+0.j, 5.5+0.j])

## complex-->int

In [7]:
li=[1.1+0.j, 3.3+0.j, 5.5+0.j]
arr=np.array(li,dtype=int)
arr

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

## complex-->float

In [ ]:
li=[1.1+0.j, 3.3+0.j, 5.5+0.j]
arr=np.array(li,dtype=float)
arr

## Dimensions in Array:

## 1) 0-D Array:
- It is in round bracket(value)

- 0-D arrays are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
arr=np.array(100)
print("Array:",arr)
print("Dimension of Array:",arr.ndim)   # ndim means= no.of dimensions

## 2) 1-D Array (uni-dimensional):

- It is a collection of 0-Dimensional Arrays.

- These are the most common and basic arrays.

In [ ]:
arr=np.array([100])
print("Array:",arr)
print("Dimension of Array:",arr.ndim)

In [ ]:
arr=np.array([100],float)
print("Array:",arr)
print("Dimension of Array",arr.ndim)

In [28]:
arr=np.array([100,200,300])
print("Array:",arr)
print("Dimension of Array:",arr.ndim)


Array: [100 200 300]
Dimension of Array: 1


## 3) 2-D Array:

- It is a collection of 1-Dimensional Arrays.

In [32]:
arr=np.array([[1,2],[3,4],[5,6]])
print(f"Array:\n{arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Shape of Array:{arr.shape}")

Array:
[[1 2]
 [3 4]
 [5 6]]
Dimension of Array:2
Shape of Array:(3, 2)


In [7]:
arr=np.array([[1,2],[3]])
print(f"Array:\n{arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Shape of Array:{arr.shape}")

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

## 4) 3-D Array:

- It is a collection of 2-Dimensional Arrays.

- These are often used to represent a 3rd order tensor.

In [30]:
arr=np.array([[[1,2],[3,4],[5,6]]])
print(f"Array:\n{arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Shape of Array:{arr.shape}")

Array:
[[[1 2]
  [3 4]
  [5 6]]]
Dimension of Array:3
Shape of Array:(1, 3, 2)


In [ ]:
arr=np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
print(f"Array:\n{arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Shape of Array:{arr.shape}")

## Indexing and Slicing:

In [34]:
arr=np.array([1,2,3,4,5])
arr[2]

3

In [38]:
arr=np.array([1,2,3,4,5])
arr[1:3]

array([2, 3])

In [ ]:
arr=np.array([[1,2,3,4,5,6,7,8,9,10],
             [10,20,30,40,50,60,70,80,90,100],
             [100,200,300,400,500,600,700,800,900,1000]])
arr

In [1]:
arr[1:2,2:4]

NameError: name 'arr' is not defined

In [ ]:
arr[1:,2:4]

# NumPy Functions:

## Convert to n-D Array:

In [9]:
arr=np.array([1,2,3])
print("Array:",arr)
print("Dimension of Array:",arr.ndim)
print("Length of Array:",len(arr))
print("Shape of Array:",arr.shape)

Array: [1 2 3]
Dimension of Array: 1
Length of Array: 3
Shape of Array: (3,)


In [11]:
arr=np.array([1,2,3],ndmin=2)
print("Array:",arr)
print("Dimension of Array:",arr.ndim)
print("Length of Array:",len(arr))
print("Shape of Array:",arr.shape)

Array: [[1 2 3]]
Dimension of Array: 2
Length of Array: 1
Shape of Array: (1, 3)


## 1) reshape(): Reshaping means changing the shape of an array.

- The shape of an array is the number of elements in each dimension.

- By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [44]:
arr=np.array([1,2,3,4])
print(f"Array: {arr}")
print(f"Dimension of Array: {arr.ndim}")
print(f"Length of Array: {len(arr)}")
print(f"Shape of Array: {arr.shape}")
print(f"Reshape of Array: \n{arr.reshape(2,2)}")

Array: [1 2 3 4]
Dimension of Array: 1
Length of Array: 4
Shape of Array: (4,)
Reshape of Array: 
[[1 2]
 [3 4]]


In [46]:
arr=np.array([1,2,3,4,5,6])
print(f"Array:{arr}")
print(f"Number of Dimensions: {arr.ndim}")
print(f"Length of Array: {len(arr)}")
print(f"Shape: {arr.shape}")
print(f"Reshaped Array:\n{arr.reshape(3,2)}")

Array:[1 2 3 4 5 6]
Number of Dimensions: 1
Length of Array: 6
Shape: (6,)
Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]


## 1-D to 3-D Conversion using reshape:

In [48]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])
print("Array:",arr)
print("Dimension of Array:",arr.ndim)
print("Length of Array:",len(arr))
print("Shape of Array:",arr.shape)
print("Reshape of Array:\n",arr.reshape(1,2,5))

Array: [1 2 3 4 5 6 7 8 9 0]
Dimension of Array: 1
Length of Array: 10
Shape of Array: (10,)
Reshape of Array:
 [[[1 2 3 4 5]
  [6 7 8 9 0]]]


## Accessing elements by 'for loop':

In [13]:
arr=np.array([[1,2],[3,4]])
for i in arr:
    print("Elements in Array:",i)

Elements in Array: [1 2]
Elements in Array: [3 4]


In [15]:
arr=np.array([[1,2],[3,4]])
for i in arr:
    for j in i:
        print("Elements in Array:",j)

Elements in Array: 1
Elements in Array: 2
Elements in Array: 3
Elements in Array: 4


## 2) np.nditer(): The function nditer() is a helping function that can be used from very basic to very advanced iterations

In [54]:
arr=np.array([1,2,3,4])
for i in np.nditer(arr):
    print("Elements in Array:",i)

Elements in Array: 1
Elements in Array: 2
Elements in Array: 3
Elements in Array: 4


In [79]:
arr=np.array([1,2,3])
a=np.nditer(arr)
a

In [81]:
next(a)

array(1)

In [83]:
next(a)

array(2)

In [85]:
next(a)

array(3)

## 3) np.ndenumerate(): Enumeration means mentioning sequence number of somethings one by one.

In [74]:
#### NORMAL ENUMERATE ####


for i,j in enumerate(list("Hi")):
    print(i,j)

0 H
1 i


In [77]:
arr=np.array(['B','Y','E'])
for i,j in enumerate(arr):
    print(i,j)

0 B
1 Y
2 E


In [ ]:
import numpy as np

In [17]:
arr=np.array(['B','Y','E'])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0,) B
(1,) Y
(2,) E


## 4) zeros(): Return an Array with all zero elements
- Syntax:
 - np.zeros(shape,dtype=float/int/complex)
- Weight Initialization
- Target Column creation

In [8]:
np.zeros(3,int)

array([0, 0, 0])

In [9]:
arr=np.zeros((2,3),int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
import pandas as pd    #data analysis

In [11]:
df=pd.DataFrame(
    {
        'Zero_Calculation':np.zeros(3,int)
    }
)
df

Zero_Calculation
0                 0
1                 0
2                 0

## 5) ones(): Return an array with all elements as one
- Syntax:
 - np.ones(shape,dtype=float/int/complex)

In [12]:
arr=np.ones(3,int)
arr

array([1, 1, 1])

## 6) arange(): NumPy arange() is one of the array creation routines based on numerical ranges

In [13]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [14]:
arr=np.arange(1,2,2)
arr

array([1])

In [15]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr=np.arange(1,6,2)
arr

array([1, 3, 5])

## 7) linspace(): Returns evenly spaced values
- Syntax:
 - np.linspace(start,end,num = 50)

In [17]:
arr=np.linspace(1,10,num=10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
arr=np.linspace(2,11,num=11)
arr

array([ 2. ,  2.9,  3.8,  4.7,  5.6,  6.5,  7.4,  8.3,  9.2, 10.1, 11. ])

In [19]:
arr=np.linspace(2,4,num=10)
arr

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

## 8) eye(): It will return an array with ones on diagonal and zeros elsewhere
- Syntax:
 - np.eye(shape,dtype=int/float/complex) # by default it is float

In [20]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arr=np.eye(3,2)
arr

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [22]:
arr=np.eye(3,dtype=complex)
arr

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

## 9) identity(): Identity matrix will be returned (i.e No of Column = No of Rows)
- Syntax:
 - np.identity(value) # by default float value is there in ans

In [23]:
arr=np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
arr=np.identity(4,3)
arr

TypeError: Cannot interpret '3' as a data type

In [21]:
arr=np.identity(3,int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 10) Random: Used to generate random values of array
- i) rand()
- ii) randint()
- iii) randn()
- iv) randf()

## i) rand(): It will return values between 0 and 1
- Syntax:
 - np.random.rand(value)

In [23]:
arr=np.random.rand(4)
arr

array([0.87459202, 0.90950015, 0.73424085, 0.90584277])

In [87]:
arr=np.random.rand(3,2)
arr

array([[0.60429779, 0.63728591],
       [0.03033291, 0.59071152],
       [0.69809055, 0.02435099]])

In [ ]:
import pandas as pd
df=pd.DataFrame(arr)
df

## ii) randint(): The randint() method takes a size parameter where you can specify the shape of an array
- Syntax:
 - np.random.randint(shape,size=(value))

In [89]:
arr=np.random.randint(1,3,size=4)
arr

array([1, 2, 1, 1])

In [ ]:
arr=np.random.randint(1,10,size=(3,5))
arr

## iii) randn(): It will return values which are normally distributed
- mean = 0 and variance = 1
- Syntax:
 - np.random.randn(shape)

In [91]:
arr=np.random.randn(2,3)
arr

array([[ 1.61405072,  2.12911754,  0.3914444 ],
       [-1.02710089, -0.81277181, -1.271984  ]])

## iv) ranf(): Return values between 0 and 1
- Syntax:
 - np.random.ranf(shape)

In [93]:
arr=np.random.ranf(3)
arr

array([0.96012534, 0.57045021, 0.12954616])

## 11) sort(): Sorting means putting elements in an ordered sequence.
- Syntax:
 - np.sort(name)
- axis 0--> Columns
- axis 1--> Rows

In [96]:
arr=np.random.randint(1,10,size=5)
arr

array([5, 1, 3, 7, 3])

In [98]:
np.sort(arr)

array([1, 3, 3, 5, 7])

In [ ]:
arr=np.random.randint(1,10,size=(5,2))
arr

In [ ]:
np.sort(arr,axis=0)   # axis=0 means--> Sorting by Columns

In [ ]:
np.sort(arr,axis=1)   # axis=1 means--> Sorting by Rows

## 12) append()
- Syntax:
 - np.append(arry1,array2,axis=None)
- axis = 1 --> Columns
- axis = 0 --> Rows

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5])
new_arr=np.append(arr1,arr2,axis=None)
new_arr

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5])
new_arr=np.append(arr1,arr2,axis=1)
new_arr

## 13) ceil(): The ceil() function rounds off decimal to nearest upper integer.
- Syntax:
 - np.ceil(value)
- 5.1 --> 6
- 5.9 --> 6
- 6.5 --> 7

In [ ]:
print(np.ceil(5.1))
print(np.ceil(5.9))

In [ ]:
np.array(np.ceil([1.1, 2.3, 3.6, 4.9, 5.99]),int)

## 14) floor(): The floor() function rounds off decimal to nearest lower integer.
- Syntax:
 - np.floor()
- 5.1--> 5
- 5.9--> 5

In [ ]:
print(np.floor(5.1))
print(np.floor(5.9))

In [ ]:
np.floor([1,2,3,4,5])

In [ ]:
np.array(np.floor([1,2,3,4]),int)

## 15) around(): The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
- Syntax:
 - np.around(value,precision=) # precision means upto what value you want your number
- E.g. round off to 1 decimal point, 3.16666 is 3.2

In [ ]:
arr=np.around(2.61110,1)
arr

In [100]:
arr=np.around(np.array([2.61110,4.56789,6.7890,8.9653]),2)
arr

array([2.61, 4.57, 6.79, 8.97])

## 16) where(): Return elements chosen from x or y depending on condition.
- Syntax:
 - np.where(condition,[x, y, ]/)

In [102]:
str1="Python and Data Science"
arr=np.array(list(str1))
print(arr)
where_command=np.where(arr=='a')
print(where_command)

['P' 'y' 't' 'h' 'o' 'n' ' ' 'a' 'n' 'd' ' ' 'D' 'a' 't' 'a' ' ' 'S' 'c'
 'i' 'e' 'n' 'c' 'e']
(array([ 7, 12, 14], dtype=int64),)
